version: "2"
services:
  app:
    container_name: web-app
    restart: always
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
    - mongo
  mongo:
    container_name: mongoDB
    image: mongo
    volumes:
      - ./app/data:/data/db
    ports:
      - "27017:27017"
