apiVersion: v1
kind: Service
metadata:
  name: node-starter
spec:
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort
  selector:
    name: node-starter
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
  selector:
    name: node-starter
